# Generated by Django 3.2.6 on 2021-09-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210831_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, default='Мы работаем над этим'),
        ),
        migrations.AddField(
            model_name='product',
            name='mode_of_application',
            field=models.TextField(blank=True, default='Мы работаем над этим'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Мы работаем над этим'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default='1'),
        ),
    ]
