# Generated by Django 3.2.6 on 2021-09-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210904_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.IntegerField(max_length=4, unique=True),
        ),
    ]
