# Generated by Django 3.2.6 on 2022-04-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210915_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=30, verbose_name='Контакт')),
                ('value', models.CharField(blank=True, max_length=300, verbose_name='Данные')),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
