# Generated by Django 3.2.6 on 2022-04-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
