# Generated by Django 3.2.6 on 2022-04-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
